### PR TITLE
Feature/optimize

### PR DESCRIPTION
**Pull request by vanderian**
wrap multiple async TXs into single async call

### CODE REVIEW

**Review by mateuszaaa — APPROVED** [review]
if it works LGTM :)

**Comment by mateuszaaa** [comment]
i think you can use mangata-node repo to run e2e tests with latest develop and particular branch from e2e repository - maybe we could use it as a precondition for merge ? 

^^ @vanderian

**Comment by vanderian** [comment]
putting this on hold in favor of `utils.batch` approach

**Comment by goncer** [comment]
3 months ol PR ? @vanderian  can we remove it?

**Pull request closed without merging**
