### PR TITLE
Add multivalidator tests

### PR DESCRIPTION
**Pull request by CodeByEddy**

### CODE REVIEW

**Comment by goncer** [comment]
@CodeByEddy  build is failing. do you mind looking at it?

**Comment by goncer** [comment]
@CodeByEddy  are you still working on this? still a draft?

**Comment by goncer** [comment]
@eddyjlsh @CodeByEddy  is this ready to be merged?

**Comment by CodeByEddy** [comment]
@goncer I'm dealing with some commit merge issues to get this in. Originally it was failing form a linting issue and fell off the radar but now it's veeeeery behind master. I'll close and re-open a PR so it's got a cleaner history for review.

**Pull request closed without merging**
